name: Combine the words
on: [push]

jobs:
  job1:
    env:
      BUILD: build
    runs-on: windows-latest
    steps: 
      - name: step 1
        env:
          TEST: test
        run: echo "GitHub Actions is a CI/CD platform that allows you to automate your $env:BUILD $env:TEST pipeline"   
      - name: step 2
        env:
          DEPLOY: deployment
        run: echo "GitHub Actions is a CI/CD platform that allows you to automate your $env:BUILD $env:TEST and $env:DEPLOY pipeline"   
